### ISSUE TITLE
Table header for device lists not sticking

### ISSUE THREAD

**Issue by gdzooks** [bean-pod/switchboard#106] opened 2020-10-27 02:45 UTC
**Operating system:** 
 
 
* Windows 10
* Google Chrome version 86.0.4240.111

**Steps to reproduce:**

1. Run the frontend (npm start)
2. Wait for the table to populate enough devices that scrolling is necessary.
3. Scroll down in the table.
* If the table doesn't have enough devices, try expanding the extra information sections to add to the height. 

**Expected result:**

* Header cells (with search boxes) should stick to the top and remain visible as you scroll down.

**Actual result:**
 
* Header cells do not stick and instead disappear as you scroll down.

**Visual proof:**
 
|  Actual  |
|:---------------:|
| 
![image](https://user-images.githubusercontent.com/22307286/97250607-b57c5380-17dc-11eb-9a85-4eb55c216e1e.png) |

| Expected |
|:---------------:|
| 
![image](https://user-images.githubusercontent.com/22307286/97250505-7cdc7a00-17dc-11eb-9148-4409384159d9.png) |

**Comment by jun-loke** [comment] 2020-11-04 18:50
Bug is caused by class being incorrectly assigned to headcells in DevicesTable.js and HeadCells.js
Is linked to warning about classvs className usage

**Closed as completed** 2020-11-23 18:54 UTC
Labels: bug, frontend
